<?php

namespace Database\Seeders;

use App\Models\Account;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $accounts = [
            [
                'account_category_id' => 1,
                'code' => '100000',
                'name' => 'Aset',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'locked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '110000',
                'name' => 'Aset Lancar',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'locked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '111000',
                'name' => 'Kas',
                'report_type' => 'neraca',
                'account_type' => 'kas',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '111000',
                'name' => 'Kas IDR',
                'report_type' => 'neraca',
                'account_type' => 'kas',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '112000',
                'name' => 'Bank',
                'report_type' => 'neraca',
                'account_type' => 'kas',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '112100',
                'name' => 'Bank Mandiri',
                'report_type' => 'neraca',
                'account_type' => 'kas',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '112200',
                'name' => 'Bank BRI',
                'report_type' => 'neraca',
                'account_type' => 'kas',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '112300',
                'name' => 'Bank BSI',
                'report_type' => 'neraca',
                'account_type' => 'kas',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '113000',
                'name' => 'Piutang Usaha',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '114000',
                'name' => 'Piutang Lain-Lain',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '115000',
                'name' => 'Persediaan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '116000',
                'name' => 'Biaya Dibayar Dimuka',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '117000',
                'name' => 'Pajak Dibayar Dimuka',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '118000',
                'name' => 'Uang Muka',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '120000',
                'name' => 'Aset Tidak Lancar',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'locked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121000',
                'name' => 'Aset Tetap',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121100',
                'name' => 'Nilai Perolehan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121101',
                'name' => 'NP-Tanah',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121102',
                'name' => 'NP-Bangunan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121103',
                'name' => 'NP-Furniture',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121104',
                'name' => 'NP-Inventaris Kantor',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121105',
                'name' => 'NP-Kendaraan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121200',
                'name' => 'Akumulasi Penyusutan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121201',
                'name' => 'AP-Tanah',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121202',
                'name' => 'AP-Bangunan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121203',
                'name' => 'AP-Furniture',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121204',
                'name' => 'AP-Inventaris Kantor',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '121205',
                'name' => 'AP-Kendaraan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '200000',
                'name' => 'Kewajiban',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'locked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '210000',
                'name' => 'Kewajiban Lancar',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'locked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '211000',
                'name' => 'Hutang BBM',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '211100',
                'name' => 'Hutang Driver',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '212000',
                'name' => 'Hutang Pajak',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '213000',
                'name' => 'Biaya Yang Masih Harus Dibayar',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '214000',
                'name' => 'Pendapatan Diterima Dimuka',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '215000',
                'name' => 'Hutang Bank',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '216000',
                'name' => 'Hutang Pembiayaan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '217000',
                'name' => 'Kewajiban Lancar Lainnya',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '217100',
                'name' => 'PPN Keluaran',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '217200',
                'name' => 'PPN Masukan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '220000',
                'name' => 'Kewajiban Tidak Lancar',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '221000',
                'name' => 'Kewajiban Jangka Panjang',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '300000',
                'name' => 'Modal',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'locked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '311000',
                'name' => 'Modal Saham A',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '312000',
                'name' => 'Modal Saham B',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '313000',
                'name' => 'Prive',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '320000',
                'name' => 'Laba Ditahan/Tahun Sebelumnya',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 1,
                'code' => '330000',
                'name' => 'Laba Tahun Berjalan',
                'report_type' => 'neraca',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 13,
                'code' => '400000',
                'name' => 'Pendapatan',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'locked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 13,
                'code' => '410000',
                'name' => 'Pendapatan Usaha',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 13,
                'code' => '500000',
                'name' => 'Harga Pokok Penjualan',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 13,
                'code' => '520000',
                'name' => 'Persediaan Barang',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 13,
                'code' => '530000',
                'name' => 'Persediaan Akhir',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '600000',
                'name' => 'Beban Usaha',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '610000',
                'name' => 'Beban Operasional',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '620000',
                'name' => 'Beban Angsurang Unit',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '621000',
                'name' => 'Biaya Pegawai',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '622000',
                'name' => 'Komunikasi dan Utilitas',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '623000',
                'name' => 'Transportasi dan Perjalanan Dinas',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '624000',
                'name' => 'Penyusutan',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '625000',
                'name' => 'Jasa & Teknik Profesional',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '626000',
                'name' => 'Beban Kantor (ATK, RTK, Dll',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '627000',
                'name' => 'Perizinan dan Legalitas',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '628000',
                'name' => 'Biaya Pengiriman',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 15,
                'code' => '629000',
                'name' => 'Beban Pajak',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 16,
                'code' => '630000',
                'name' => 'Beban Lain-lain',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 17,
                'code' => '700000',
                'name' => 'Pendapatan Diluar Usaha',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 17,
                'code' => '710000',
                'name' => 'Pendapatan Jasa Giro',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 17,
                'code' => '720000',
                'name' => 'Pendapatan Lainnya',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'kredit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 16,
                'code' => '800000',
                'name' => 'Beban Diluar Usaha',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 16,
                'code' => '810000',
                'name' => 'Biaya Administrasi Bank',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 16,
                'code' => '820000',
                'name' => 'Biaya Pajak Giro',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 16,
                'code' => '830000',
                'name' => 'Beban Lain-Lain',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],
            [
                'account_category_id' => 16,
                'code' => '910000',
                'name' => 'Pajak Penghasilan',
                'report_type' => 'laba rugi',
                'account_type' => 'umum',
                'default_balance' => 'debit',
                'lock_status' => 'unlocked',
                'status' => 'active',
            ],


        ];

        Account::insert($accounts);
    }
}
